### ISSUE TITLE
Blank screen on iOS Devices

### ISSUE THREAD

**Issue by ndi123** [eneiluj/cospend-nc#33]
Hi,

after updating from 1.2.7 to 1.2.8 i only see a blank white screen on iOS devices (iPhone and iPad) when opening the Cospend Tab in my NextCloud (20.0.6). Tested with Chrome and Safari.

No problems on a Win 10 notebook.

**Comment by eneiluj** [comment]
Hi thanks for the bug report. I'll try to find some apple devices and reproduce the bug.

In the meantime, could you check if there is any error in nextcloud.log when loading Cospend? And if possible in this mobile context, could you check the browser error log?

**Comment by ndi123** [comment]
Thank you for the reply. 

I just it tested on another Nextcloud installation (fresh installation of Cospend) and i could reproduce it. i wanted to exclude that it concerns only my instance.

There are no warnings/errors in the nextcloud.log. I enabled the debug log, but it also seems to be uninteresting:

`{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:35+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"contacts","method":"GET","url":"/index.php/apps/cospend/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:35+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"files_sharing","method":"GET","url":"/index.php/apps/cospend/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:35+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"twofactor_totp","method":"GET","url":"/index.php/apps/cospend/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"scss_cacher","method":"GET","url":"/index.php/apps/cospend/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"scss_cacher","method":"GET","url":"/index.php/apps/cospend/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"scss_cacher","method":"GET","url":"/index.php/apps/cospend/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"scss_cacher","method":"GET","url":"/index.php/apps/cospend/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"scss_cacher","method":"GET","url":"/index.php/apps/cospend/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"scss_cacher","method":"GET","url":"/index.php/apps/cospend/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"hj9aTSn167Imt51idJtP","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"scss_cacher","method":"GET","url":"/index.php/apps/cospend/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"BPea5K8PXbRNQ7uMiyTU","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"contacts","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"BPea5K8PXbRNQ7uMiyTU","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"files_sharing","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"BPea5K8PXbRNQ7uMiyTU","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"twofactor_totp","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"Ws3iZ6eyrCdiNGImUqzk","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"contacts","method":"GET","url":"/ocs/v2.php/search/providers?from=%2Fapps%2Fcospend%2F","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"Ws3iZ6eyrCdiNGImUqzk","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"files_sharing","method":"GET","url":"/ocs/v2.php/search/providers?from=%2Fapps%2Fcospend%2F","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"Ws3iZ6eyrCdiNGImUqzk","level":0,"time":"2021-01-28T12:43:36+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxx","app":"twofactor_totp","method":"GET","url":"/ocs/v2.php/search/providers?from=%2Fapps%2Fcospend%2F","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","version":"20.0.6.1"}`

Unfortunately there is no debug log directly on ios devices. I have never dealt with remote debug on iOS devices.

**Comment by eneiluj** [comment]
It's weird. Almost nothing was changed in v1.2.8 regarding the UI. The only things that could cause trouble are:
* a change of the `body` style
* the upgrade of a few JS libraries

I really need the JS error log to understand what happens.

Another option to make progress here would be that I make multiple nightly builds in which those things are removed and you try them. I don't have time for that right now.

**Comment by eneiluj** [comment]
Here is a procedure to get the repository and revert the commits which I think could be the cause. If you don't feel comfortable with that, I'll produce the nightly builds some day. This won't delete anything in the database and you can go back to official release after that. You need `npm` to build the sources.

Considering you have access to a bash-like shell on your server:
``` bash
cd /var/www/.../nextcloud/apps
# remove the official release
rm -r cospend
# get the dev version
git clone https://github.com/eneiluj/cospend-nc cospend
cd cospend
# undo the commit where the body style was changed and build
git revert fc20d89c5413a3c21d2cd2ec508f7fc12164245b --no-edit
npm ci && npm run dev
# now you can check if Cospend works on your apple thing
# if it still does not work, let's revert the commit where the JS libs were upgraded
git revert 18b53de9e1fddb3b283785eddb9b5045b17d6279 --no-edit
npm ci && npm run dev
# check again
```
Then to go back to official releases
```
cd ..
rm -rf cospend
```
And reinstall the app from Nextcloud app settings.

**Comment by ndi123** [comment]
I needed to revert both commits to get Cospend working again on my "apple things".

Also i digged into iOS remote debugging. There is this error in the current version, which i do not see in the working version:

![grafik](https://user-images.githubusercontent.com/34609222/106285604-f86b1e80-6244-11eb-8f1c-0c8394b0a26f.png)

**Comment by eneiluj** [comment]
Thanks a lot for the feedback.

So you mean you reverted the first and it was not working. Then it started working when you reverted the second (JS libs upgrade). Right?

I found out in NC-Vue public chatroom that @nextcloud/vue v3.4.0 has problems with Safari and this should be fixed with latest release.

Let's confirm that! Could you get back to my master branch:
```
git reset --hard 18b53de9e1fddb3b283785eddb9b5045b17d6279
```
Then set the version of "@nextcloud/vue" to "3.5.4" instead of "3.4.0" in `package.json` and then build again like that:
```
npm install && npm run dev
```

> "apple things"
:grin:

**Comment by ndi123** [comment]
> So you mean you reverted the first and it was not working. Then it started working when you reverted the second (JS libs upgrade). Right?

Absolutely right 

> Then set the version of "@nextcloud/vue" to "3.5.4" instead of "3.4.0" in package.json

I bumped "@nextcloud/vue" to 3.5.4 (also had to edit package-lock.json) but the blank page still persists 😢

**Comment by eneiluj** [comment]
> also had to edit package-lock.json

If you run `npm install` then `package-lock.json` is automatically modified. Are you sure you have built the project again (`npm run dev`) after the lib bump?

**Comment by ndi123** [comment]
Sorry, i mixed up npm ci an you documented npm install (i am not familiar with npm). After npm install and npm run dev Cospend is back on Safari 👍

**Comment by eneiluj** [comment]
You are the best! Nice remote debugging session. I'll publish a fixed release very soon.

**Comment by eneiluj** [comment]
v1.2.9 is out. Thanks again for helping to kill this bug.
